### ISSUE TITLE
Set the data-sortvalue value dynamically?

### ISSUE THREAD

**Issue by tetsujin1979** [myspace-nu/jquery.fancyTable#35]
Is it possible to set the "data-sortvalue" value dynamically? 
As in, pass in a call to a javascript function, e.g. `<td data-sortvalue="textToNumber('Text')">Text</td>`
where the `textToNumber()` function converts text to a value used in sorting?

**Comment by myspace-nu** [comment]
You can set the data-sortvalue value with JavaScript using the [dataset](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes)
`document.querySelector("#my_table_cell").dataset.sortvalue = "somevalue"`
or using [jQuery attr](https://api.jquery.com/attr/)
`$("#my_table_cell").attr("data-sortvalue","somevalue")`

You can also hijack the sort function and write your own [sort function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) not limited to the data-sortvalue attribute
```
$("#your_table").fancyTable({
	sortFunction: function(a, b, fancyTableObject, rowA, rowB){
		// your custom sort logic
	},
	// more settings
})
```

Closing this ticket since it is not an fancyTable issue.
